export const imageBasicDoor = [
  { src: "/img/basicDoor/basic-1.png", alt: "Basic Door 1" },
  { src: "/img/basicDoor/basic-2.png", alt: "Basic Door 2" },
  { src: "/img/basicDoor/basic-3.png", alt: "Basic Door 3" },
  { src: "/img/basicDoor/basic-4.png", alt: "Basic Door 4" },
  { src: "/img/basicDoor/basic-5.png", alt: "Basic Door 5" },
  { src: "/img/basicDoor/basic-6.png", alt: "Basic Door 6" },
  { src: "/img/basicDoor/basic-7.png", alt: "Basic Door 7" },
  { src: "/img/basicDoor/basic-8.png", alt: "Basic Door 8" },
  { src: "/img/basicDoor/basic-9.png", alt: "Basic Door 9" },
  { src: "/img/basicDoor/basic-10.png", alt: "Basic Door 10" },
  { src: "/img/basicDoor/basic-11.png", alt: "Basic Door 11" },
  { src: "/img/basicDoor/basic-12.png", alt: "Basic Door 12" },
  { src: "/img/basicDoor/basic-13.png", alt: "Basic Door 13" },
  { src: "/img/basicDoor/basic-14.png", alt: "Basic Door 14" },
  { src: "/img/basicDoor/basic-15.png", alt: "Basic Door 15" },
  { src: "/img/basicDoor/basic-16.png", alt: "Basic Door 16" },
  { src: "/img/basicDoor/basic-17.png", alt: "Basic Door 17" },
  { src: "/img/basicDoor/basic-18.png", alt: "Basic Door 18" },
  { src: "/img/basicDoor/basic-19.png", alt: "Basic Door 19" },
  { src: "/img/basicDoor/basic-20.png", alt: "Basic Door 20" },
  { src: "/img/basicDoor/basic-21.png", alt: "Basic Door 21" },
  { src: "/img/basicDoor/basic-22.png", alt: "Basic Door 22" },
  { src: "/img/basicDoor/basic-23.png", alt: "Basic Door 23" },
  { src: "/img/basicDoor/basic-24.png", alt: "Basic Door 24" },
  { src: "/img/basicDoor/basic-25.png", alt: "Basic Door 25" },
];
